# Customer Experience Analytics for Fintech Apps
## Task 1: Data Collection and Preprocessing

### 10 Academy — Artificial Intelligence Mastery
### Week 2 Challenge

Author: Lalise Fufi
Date: May 2026

1. Import Libraries Cell

In [1]:
# Core libraries
import pandas as pd
import numpy as np
import re
from datetime import datetime

# The star of the show
from google_play_scraper import app, reviews, Sort

print("Libraries loaded successfully!")

Libraries loaded successfully!

2. Define Bank Applications Cell

In [2]:
# Google Play application IDs

apps = {
    "Commercial Bank of Ethiopia": "com.combanketh.mobilebanking",
    "Bank of Abyssinia": "com.boa.boaMobileBanking",
    "Dashen Bank": "com.dashen.dashensuperapp"
}

3. Scraping Google Play Reviews

We collect:

- Review text
- Rating
- Review date
- Bank name
- Source

Target:
- Minimum 400 reviews per bank

In [3]:
all_reviews = []

for bank_name, app_id in apps.items():

    print(f"Scraping reviews for {bank_name}...")

    result, continuation_token = reviews(
        app_id,
        lang='en',
        country='et',
        sort=Sort.NEWEST,
        count=500
    )

    print(f"Collected {len(result)} reviews")

    for review in result:

        all_reviews.append({
            "review_id": review.get("reviewId"),
            "review": review.get("content"),
            "rating": review.get("score"),
            "date": review.get("at"),
            "bank": bank_name,
            "source": "Google Play"
        })

print("Scraping completed!")

Scraping reviews for Commercial Bank of Ethiopia...
Collected 500 reviews
Scraping reviews for Bank of Abyssinia...
Collected 500 reviews
Scraping reviews for Dashen Bank...
Collected 500 reviews
Scraping completed!

4. Create DataFrame Cell

In [4]:
df = pd.DataFrame(all_reviews)

print("Dataset Shape:")
print(df.shape)

df.head()

Dataset Shape:
(1500, 6)

,review_id,review,rating,date,bank,source
0,363a5616-ed3d-4274-85ee-77071067f81d,wow,5,2026-05-13 12:19:17,Commercial Bank of Ethiopia,Google Play
1,56185597-d29b-4a60-a0fb-6783638230a7,Good application,2,2026-05-13 11:27:52,Commercial Bank of Ethiopia,Google Play
2,35efe702-40c9-4e46-ad67-7574ab9ef42d,"Nice, but I can't get some recently transactio...",5,2026-05-13 11:21:48,Commercial Bank of Ethiopia,Google Play
3,b41cb49d-59d3-41b8-bbb2-b1952005951b,Very Secure but very poor interface and limite...,1,2026-05-13 11:11:25,Commercial Bank of Ethiopia,Google Play
4,22026bb2-c9c4-4040-892b-2a77ebee48b7,very nice 100%,5,2026-05-13 05:12:17,Commercial Bank of Ethiopia,Google Play

In [5]:
print("Missing Values:")

df.isnull().sum()

Missing Values:

review_id    0
review       0
rating       0
date         0
bank         0
source       0
dtype: int64

In [6]:
duplicate_count = df.duplicated(subset=["review_id"]).sum()

print(f"Duplicate Reviews: {duplicate_count}")

Duplicate Reviews: 0

## Data Quality Check

The dataset was checked for missing values and duplicate reviews.

- Missing Values: `0`
- Duplicate Reviews: `0`

This indicates that the scraped data is clean, complete, and ready for preprocessing and analysis.

5. Preprocessing Markdown

## Data Preprocessing

Preprocessing steps:

1. Remove duplicate reviews
2. Drop rows with missing review text or rating
3. Standardize dates
4. Keep required columns only

In [ ]:
#Remove Duplicates Cell
df = df.drop_duplicates(subset=["review_id"])

print("Shape after removing duplicates:")
print(df.shape)

Shape after removing duplicates:
(1500, 6)

In [8]:
#Handle Missing Values Cell
df = df.dropna(subset=["review", "rating"])

print("Shape after removing missing values:")
print(df.shape)

Shape after removing missing values:
(1500, 6)

## Duplicate and Missing Value Handling

After removing duplicate reviews, the dataset shape remained `(1500, 6)`, indicating that no duplicate records were found.

After handling missing values, the dataset shape also remained `(1500, 6)`, showing that there were no missing values in the `review` and `rating` columns.

This confirms that the dataset is clean and complete for further analysis.

In [9]:
#Normalize Dates Cel
df["date"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")

df.head()

,review_id,review,rating,date,bank,source
0,363a5616-ed3d-4274-85ee-77071067f81d,wow,5,2026-05-13,Commercial Bank of Ethiopia,Google Play
1,56185597-d29b-4a60-a0fb-6783638230a7,Good application,2,2026-05-13,Commercial Bank of Ethiopia,Google Play
2,35efe702-40c9-4e46-ad67-7574ab9ef42d,"Nice, but I can't get some recently transactio...",5,2026-05-13,Commercial Bank of Ethiopia,Google Play
3,b41cb49d-59d3-41b8-bbb2-b1952005951b,Very Secure but very poor interface and limite...,1,2026-05-13,Commercial Bank of Ethiopia,Google Play
4,22026bb2-c9c4-4040-892b-2a77ebee48b7,very nice 100%,5,2026-05-13,Commercial Bank of Ethiopia,Google Play

In [10]:
#Keep Required Columns Cell
cleaned_df = df[[
    "review",
    "rating",
    "date",
    "bank",
    "source"
]]

cleaned_df.head()

,review,rating,date,bank,source
0,wow,5,2026-05-13,Commercial Bank of Ethiopia,Google Play
1,Good application,2,2026-05-13,Commercial Bank of Ethiopia,Google Play
2,"Nice, but I can't get some recently transactio...",5,2026-05-13,Commercial Bank of Ethiopia,Google Play
3,Very Secure but very poor interface and limite...,1,2026-05-13,Commercial Bank of Ethiopia,Google Play
4,very nice 100%,5,2026-05-13,Commercial Bank of Ethiopia,Google Play

6. Dataset Summary Cell

In [11]:
print("Final Dataset Shape:")
print(cleaned_df.shape)

print("\nReviews Per Bank:")
print(cleaned_df["bank"].value_counts())

Final Dataset Shape:
(1500, 5)

Reviews Per Bank:
bank
Commercial Bank of Ethiopia    500
Bank of Abyssinia              500
Dashen Bank                    500
Name: count, dtype: int64

7. Save CSV Cell

In [12]:
cleaned_df.to_csv("fintech_reviews_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [13]:
cleaned_df.sample(5)

,review,rating,date,bank,source
1239,Nice,5,2025-12-02,Dashen Bank,Google Play
1408,"its amazing app, visually stunning",5,2025-09-26,Dashen Bank,Google Play
1176,this app good,5,2026-01-09,Dashen Bank,Google Play
684,what is wrong these app ?,1,2026-01-30,Bank of Abyssinia,Google Play
527,the app does not show my account balance corre...,1,2026-04-19,Bank of Abyssinia,Google Play

## Sample Review Inspection

A random sample of reviews was inspected to verify the quality and structure of the cleaned dataset.

The sample shows that the dataset contains:

- Positive and negative user feedback
- Reviews from all three banks
- Properly formatted dates
- Correct bank labels and source information

This confirms that the preprocessing steps were applied successfully and the dataset is ready for further sentiment and thematic analysis.

8. Conclusion

Task 1 was completed successfully.

A total of 1,500 Google Play Store reviews were collected from:

- Commercial Bank of Ethiopia
- Bank of Abyssinia
- Dashen Bank

The dataset was cleaned by:

- Removing duplicate reviews
- Handling missing values
- Standardizing date formats
- Verifying data quality

The final cleaned dataset contains 1,500 reviews with balanced distribution across all three banks and is ready for:

- Sentiment Analysis
- Thematic Analysis
- PostgreSQL Database Storage
- Visualization and Business Insights